jet-lab/jet-engine

src/market.ts, src/reserve.ts
=> (JET-156) Fix Market Account Decoding for Devnet

.github/CODEOWNERS, .husky/pre-commit, package-lock.json, package.json
add husky pre-commit hooks for formatting, linting and tests
[JET-160](https://jetprotocol.atlassian.net/jira/software/projects/JET/boards/1?selectedIssue=JET-160)
=> Add Pre-Commit Hooks

.prettierrc, src/client.ts, src/index.ts, src/layout.ts, src/market.ts, src/obligation.ts, src/p2p/index.ts, src/p2p/types.ts, src/reserve.ts, src/types.ts, src/user.ts, src/util.ts, tests/client.spec.ts, types/buffer-layout.d.ts
[JET-212](https://jetprotocol.atlassian.net/browse/JET-212)
=> Obligation Position Decoding

README.md
Signed-off-by: Mitchel Kelonye vbstreetz@gmail.com
=> fix(readme): typo in example code

src/pools/idl.ts, src/pools/user.ts
integrations for the following instructions
1. close deposit account
2. close collateral account
3. close loan account 
4. close obligation
updates pool idl
=> JET-347 Close account instructions to return rent

package-lock.json, package.json, src/common/accountParser.ts, src/common/index.ts, src/pools/client.ts, src/pools/layout.ts, src/pools/market.ts, src/pools/reserve.ts, src/pools/user.ts, src/pools/util.ts, src/staking/client.ts, src/staking/idl.ts, src/staking/index.ts, src/staking/stakeAccount.ts, src/staking/stakePool.ts, src/staking/unbondingAccount.ts, tests/client.spec.ts, tests/market.spec.ts, tests/utilities.spec.ts, tools/create_stake_pool.ts
New style for the lib. Really happy how it's turning out. Especially stakeAccount.ts
=> Staking: Init pool, add stake

examples/user_position.ts, src/pools/obligation.ts
fixed collateralRatio and utilizationRate being calculated incorrectly 
fixed depositedValue, collateralValue, and loanedValue incremented with NaN
fixed Anchor Wallet being broken and affecting our example(temp fix)
=> JET-441 Fix deposit notes

src/staking/unbondingAccount.ts
-Get array of unbondingAccounts
-sums BN
-converts BN to number
-if undefined, return 0
=> JET-482 Added unbonding amount total

package-lock.json, package.json, src/staking/unbondingAccount.ts
=> Fix unbonding seed

package-lock.json, package.json, src/staking/unbondingAccount.ts
And fixed an issue using reduce() on an empty array
=> v0.2.17 Withdraw unbonded

package-lock.json, package.json
I've updated the package.json and published
=> 0.2.20 Airdrops by Qiqi

src/staking/stakeAccount.ts, src/staking/stakePool.ts
Also added calculation for amount of votes per share in governance
=> Change bn to u64 to match back-end

src/rewards/airdrop.ts
=> [GVN-266] fix loading airdrop

src/staking/unbondingAccount.ts
- Update to read unbonding values as shares instead of tokens
- Reintroduce unbonding accounts total tally calculation
=> Read unbonding shares instead of tokens

src/staking/unbondingAccount.ts
- Get `UnbondingAccount.tokens` using unbonding stakepool share to token conversion
- Update `useUnbondingAmountTotal` to use tokens instead of shares
=> GVN-298 Calculate shares as tokens

.github/CODEOWNERS, package-lock.json, package.json, src/rewards/airdrop.ts, src/staking/idl.ts, src/staking/unbondingAccount.ts
=> [GVN-380] v0.2.44 update cancelUnbond ix

src/staking/unbondingAccount.ts
Pass correct `VoterWeightRecord` value in `withCancelUnbond`
=> Fix withCancelUnbond instruction

src/rewards/airdrop.ts
Add check to airdrop claim with derived addresses
=> Add check to airdrop claim

package-lock.json, package.json, src/common/accountParser.ts, src/common/associatedToken.ts, src/common/index.ts, src/index.ts, src/margin/client.ts, src/margin/config.ts, src/margin/index.ts, src/margin/marginAccount.ts, src/margin/state.ts, src/marginPool/marginPool.ts, src/pools/layout.ts, tests/client.spec.ts, tests/market.spec.ts
Load all pools found in config.
Decoding margin account positions array with buffer-layout.
Typessafe config.
Switch AssociatedToken args from PublicKey to Address
=> v0.3.3 Account positions

examples/user_position.ts, package-lock.json, package.json, src/auth/auth.ts, src/common/associatedToken.ts, src/common/tokenFaucet.ts, src/margin/marginAccount.ts, src/pools/reserve.ts, src/pools/user.ts, src/rewards/distribution.ts, src/staking/stakeAccount.ts, src/staking/unbondingAccount.ts, tests/client.spec.ts, tests/market.spec.ts
=> v0.3.6: Anchor 0.24.2
